import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/userContext";
import { CheckboxProvider } from "@/context/checkboxcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CheckboxProvider>
      <UserProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </UserProvider>
    </CheckboxProvider>
  );
}
